---
# tasks file for roles/apache
- name: install apache
  package:
    name: "{{ web_package }}" #from group_vars
    state: latest
    
- name: serverName
  lineinfile:
    path: "{{ web_path }}"
    regexp: '^ServerName'
    insertafter: '^#ServerName'
    line: "ServerName {{ ansible_fqdn }}:80"
  notify: restart_web

- name: securing document root permissions
  file:
    path: '/var/www/html'
    mode: '3750'
    owner: 'root'
    group: "{{ web_group }}" #from group vars

- name: index page
  copy:
    content: "Welcome to {{ ansible_fqdn }} \n"
    dest: '/var/www/html/index.html'
    mode: '640'
    owner: "{{ web_group }}" #from group vars

- name: firewalld for centos
  systemd:
    name: firewalld
    state: started
    enabled: true
  when: ansible_distribution == 'CentOS'

- name: open http on centos
  firewalld:
    service: http
    permanent: true
    immediate: true #runtime state
    state: enabled
  when: ansible_distribution == 'CentOS'

- name: ufw ubuntu
  systemd:
    name: ufw
    state: started
    enabled: true
  when: ansible_distribution == 'Ubuntu'

- name: open http on ubuntu
  ufw:
    port: "{{ item }}"
    rule: allow
    state: enabled
  when: ansible_distribution == 'Ubuntu'
  loop:
    - http
    - ssh
    
- name: enable apache
  systemd:
    name: "{{ web_service }}" #from group_vars
    state: started
    enabled: true