---
- name: Create user
  hosts: webservers
  gather_facts: false
  become: true
  tasks:
    # - name: task 1
    #   debug:
    #     msg: "hello {{ ansible_fqdn }}"
    
    # - name: create users
    #   user:
    #     name: "{{ item }}"
    #     password: "{{ 'somesecurepassword' | password_hash('sha512', 'A512') }}"
    #     update_password: on_create
    #   loop:
    #     - 'bob'
    #     - 'jodi'
    #     - 'joe'
    #   when: user_create == 'yes'

    # - name: delete users
    #   user:
    #     name: "{{ item }}"
    #     state: absent
    #     remove: true
    #   loop:
    #     - 'bob'
    #     - 'jodi'
    #     - 'joe'
    #   when: user_create == 'no'

    # - name: create user by prompt
    #   user:
    #     name: "{{ user_name }}"

    - name: create user by prompt (ansible-playbook -e "user_create=yes user_name=bob" sample.yaml)
      user:
        name: "{{ user_name }}"
        password: '$6$BQsy/HoFxDIcju2B$CLOqf8VP.ZoA0zv/UJFPTxZLA2BRpR8p1mklWZf0614uQIdQT1GlgaHM6rH4CZmTuMgLJ7deMb5YduOKfjHCR/'
        update_password: on_create
      when: 
        user_create == 'yes'

    - name: delete user by prompt (ansible-playbook -e "user_create=no user_name=bob" sample.yaml)
      user:
        name: "{{ user_name }}"
        state: absent
        remove: true
      when:
        user_create == 'no'

    



