---
- hosts: all
  gather_facts: yes

  tasks:
    - name: Change the hostname
      hostname:
        name="{{ inventory_hostname }}" # Magic Variable
      when:
        ansible_fqdn != ansible_host
      become: yes
      register: res
    - debug:
        var: res

    - name: Fix /etc/hosts removing the old hostname
      tags:
        - hosts
      lineinfile:
        state=present
        dest=/etc/hosts
        line="{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
        regexp="^{{ ansible_default_ipv4.address }}"
      when:
        ansible_fqdn != inventory_hostname

    - name: Uptime before reboot
      shell: uptime
      register: uptime_pre_reboot
    - debug:
        msg: "{{ uptime_pre_reboot.stdout }}"

    - name: restart machine
      reboot:
      become: yes
      register: res
      
    - name: Wait for {{ inventory_hostname }} to come back up
      wait_for_connection:
        delay: 60
        timeout: 120
        
    - name: Uptime after reboot
      shell: uptime
      register: uptime_post_reboot
    - debug:
        msg: "{{ uptime_post_reboot.stdout }}"

    # gathering the facts again for assertion task
    - name: do facts module to get latest information
      setup:  

    - name: Validate ansible_fqdn == inventory_hostname
      tags:
        - validate
      assert:
        that:
          ansible_fqdn == inventory_hostname