---
# tasks file for roles/php
- name: install php
  package:
    name: php
    state: latest
  notify: restart_web #calling the handler to restart service

- name: copy index.php
  copy:
    src: index.php
    dest: '/var/www/html/index.php'
    mode: '640' #as string and not as integer thus the quotes
    group: "{{ web_group }}"